name: Dependabot Auto Merge

on:
  pull_request:

jobs:
  automerge:
    name: Automerge
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.2.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
